version: '3.9'

services:
  redis-db:
    image: 'redis:alpine'
    container_name: redis-db
    command: redis-server
    volumes:
      - ../data/redis-data:/data
    networks:
      ethnet:
        ipv4_address: 172.20.0.105